__merge__: ../../api/comp_method.yaml

functionality:
  name: scglue
  info:
    label: scglue
    summary: "GRN inference using scglue"
    description: |
      GRN inference using scglue. 
    documentation_url: https://scglue.readthedocs.io/
  arguments:
    - name: --multiomics_rna
      __merge__: ../../api/file_multiomics_rna_h5ad.yaml
      required: True
      direction: input
    - name: --multiomics_atac
      __merge__: ../../api/file_multiomics_atac_h5ad.yaml
      required: false
      direction: input
    - name: --prediction
      __merge__: ../../api/file_prediction.yaml
      required: true
      direction: output

    - name: --annotation_file
      type: file
      example: resources/grn-benchmark/supp/gencode.v45.annotation.gtf.gz
      info:
        label: annotation
        summary: "annotation file"
        file_type: gtf.gz
        columns: 
          - name: gene_name
            type: string
            required: false
          - name: annotation
            type: string
            required: false
      required: false
      direction: input
    - name: --motif_file
      type: file
      example: resources/grn-benchmark/supp/JASPAR2022-hg38.bed.gz
      info:
        label: tfmotif
        summary: "Tf motif info"
        file_type: bed.gz
        columns: 
          - name: tf_name
            type: string
            required: false
          - name: region
            type: string
            required: false
      required: false
      direction: input
    - name: --temp_dir
      type: string
      direction: input
      default: output/figr/
    - name: --num_workers
      type: integer
      direction: input
      default: 4
      
  resources:
    - type: python_script
      path: script.py
    - path: main.py

platforms:
  - type: docker
    # image: janursa/scglue:19-08-2024
    image: nvcr.io/nvidia/pytorch:24.06-py3
    setup:
      - type: python
        packages: [ scglue==0.3.2, pyscenic==0.12.1, numpy==1.23.4, scanpy, networkx, pyarrow, cytoolz, scikit-misc, cuda-python]
      - type: apt
        packages: [bedtools]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
