__merge__: ../../api/comp_method.yaml

functionality:
  name: scenicplus
  info:
    label: scenicplus
    summary: "GRN inference using scenicplus"
    description: |
      GRN inference using scenicplus
    documentation_url: https://scenicplus.readthedocs.io/en/latest/pbmc_multiome_tutorial.html

  resources:
    - type: python_script
      path: script.py
    - path: main.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [  ]
      - type: python
        git: [ https://github.com/aertslab/scenicplus ]


  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
