functionality:
  name: sc_counts
  namespace: "perturbation"
  info:
    label: sc_counts
    summary: "Porcesses sc counts of perturbation data to generate pseudobulked"
    description: |
      It conducts QC on sc level to remove low quality cell and genes. 
      Then, sc counts are pseudobulked and filtered for outliers compounds, samples with low quality cells, and genes with low coverage. 
      Finally, it normalized the counts data. 
    
  arguments:
    - name: --perturbation_counts
      type: file 
      required: false
      direction: input
      default: resources_test/datasets_raw/perturbation_counts.h5ad 
      
    - name: --perturbation_data_f
      type: file
      info:
        label: perturbation
        summary: "Perturbation dataset for benchmarking."
        file_type: h5ad
        slots:
          layers:
            - name: n_counts
              type: double
              description: "Pseudobulked values using mean approach"
              required: true
      required: false
      direction: output
      default: resources_test/grn-benchmark/perturbation_data.h5ad 
      

  resources:
    - type: python_script
      path: script.py


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [ sctk==0.2.2]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
