__merge__: ../../api/comp_method.yaml

functionality:
  name: celloracle
  namespace: "grn_methods"
  info:
    label: celloracle
    summary: "GRN inference using celloracle"
    description: |
      GRN inference using celloracle. 
    documentation_url: https://morris-lab.github.io/CellOracle.documentation/
  # arguments:
    
      
  resources:
    - type: python_script
      path: script.py
    - path: main.py


platforms:
  - type: docker
    # image: ghcr.io/openproblems-bio/base_python:1.0.4
    image: kenjikamimoto126/celloracle_ubuntu:0.18.0
    # setup:
    #   - type: python
    #     packages: [celloracle==0.14.0, genomepy==0.16.1]
    #   - type: apt
    #     packages: []

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
