__merge__: ../../api/comp_method.yaml

functionality:
  name: celloracle
  info:
    label: celloracle
    summary: "GRN inference using celloracle"
    description: |
      GRN inference using celloracle. 
    documentation_url: https://morris-lab.github.io/CellOracle.documentation/
  arguments:
    - name: --multiomics_rna
      __merge__: ../../api/file_multiomics_rna_h5ad.yaml
      required: false
      direction: input
      default: resources_test/grn-benchmark/multiomics_rna.h5ad
    - name: --multiomics_atac
      __merge__: ../../api/file_multiomics_atac_h5ad.yaml
      required: false
      direction: input
      default: resources_test/grn-benchmark/multiomics_atac.h5ad
    - name: --prediction
      __merge__: ../../api/file_prediction.yaml
      required: false
      direction: output
      default: resources_test/grn-benchmark/perturbation_data.h5ad

    - name: --temp_dir
      type: string
      direction: input
      default: output/celloracle/
    - name: --num_workers
      type: integer
      direction: input
      default: 1
      
  resources:
    - type: python_script
      path: script.py
    - path: main.py


platforms:
  - type: docker
    # image: ghcr.io/openproblems-bio/base_python:1.0.4
    image: kenjikamimoto126/celloracle_ubuntu:0.18.0
    # setup:
    #   - type: python
    #     packages: [celloracle==0.14.0, genomepy==0.16.1]
    #   - type: apt
    #     packages: []

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
