functionality:
  name: multiome
  info:
    label: multiome
    summary: "Download multiome, splits to rna and atac and saves seperately."

  arguments:
    - name: --multiome_counts
      type: file 
      required: True
      direction: input
    - name: --multiomics_rna
      type: file 
      required: true
      direction: output
    - name: --multiomics_atac
      type: file 
      required: true
      direction: output

  resources:
    - type: python_script
      path: script.py


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
