functionality:
  name: sc_counts
  info:
    label: sc_counts
    summary: "Porcesses sc counts of perturbation data to generate pseudobulked"
    description: |
    "
    It conducts QC on sc level to remove low quality cell and genes. 
    Then, sc counts are pseudobulked and filtered for outliers compounds, samples with low quality cells, and genes with low coverage. 
    Finally, it normalized the counts data. 
    "

  arguments:
    - name: --sc_counts
      type: file 
      required: True
      direction: input
    - name: --perturbation_data
      type: file 
      required: true
      direction: output
      

  resources:
    - type: python_script
      path: script.py


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
