
functionality:
  name: run_grn_inference
  namespace: "workflows"
  info:
    label: run_grn_inference
    summary: "Infers GRNs from multiomics data using GRN inference methods."

  argument_groups:
    - name: Inputs
      arguments:
        - name: --multiomics_rna
          type: file 
          required: true
          direction: input
          default: resources/grn-benchmark/multiomics_rna.h5ad
          description: single cell multiomics rna data 

        - name: --multiomics_atac
          type: file 
          required: true
          direction: input
          default: resources/grn-benchmark/multiomics_atac.h5ad
          description: single cell multiomics atac data

    - name: Outputs
      arguments:
        - name: "--scores"
          type: file
          required: true
          direction: output
          description: A yaml file containing the scores of each of the methods
          default: score_uns.yaml
        - name: "--method_configs"
          type: file
          required: true
          direction: output
          default: method_configs.yaml
        - name: "--metric_configs"
          type: file
          required: true
          direction: output
          default: metric_configs.yaml
        - name: "--dataset_uns"
          type: file
          required: true
          direction: output
          default: dataset_uns.yaml
        - name: "--task_info"
          type: file
          required: true
          direction: output
          default: task_info.yaml
    - name: Arguments
      arguments:
        - name: "--method_ids"
          type: string
          multiple: true
          description: A list of method ids to run. If not specified, all methods will be run.
        - name: "--metric_ids"
          type: string
          multiple: true
          description: A list of metric ids to run. If not specified, all metric will be run.    
    
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  dependencies:
    # - name: common/extract_metadata
    #   repository: openproblemsv2
    - name: grn_methods/dummy 
    - name: grn_methods/celloracle 
    - name: metrics/regression_1
    # - name: grn_methods/figr
    # - name: grn_methods/scglue
  # repositories:
  #   - name: openproblemsv2
  #     type: github
  #     repo: openproblems-bio/openproblems-v2
  #     tag: main_build
platforms:
  - type: nextflow
    directives:
      label: [ midtime, midmem, lowcpu ]
