functionality:
  name: batch_correction_scgen
  info:
    label: batch_correction_scgen
    summary: "Correct batch effects using scgen"
    

  arguments:
    - name: --perturbation_data
      type: file 
      required: true

      

  resources:
    - type: python_script
      path: script.py


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
