functionality:
  name: cistopic
  info:
    label: cistopic
    summary: "creates cistopic"


  resources:
    - type: r_script
      path: script.R


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    # setup:
    #   - type: r
    #     packages: [dplyr, FNN, chromVAR, doParallel, BuenColors, FigR, BSgenome.Hsapiens.UCSC.hg38]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
