__merge__: ../../api/comp_method.yaml

functionality:
  name: dummy
  info:
    label: dummy
    summary: "FILL IN: A one sentence summary of this method."
    description: |
      A dummy method that contains the format of a real GRN inference method.
    documentation_url: https://url.to/the/documentation
    repository_url: https://github.com/organisation/repository
  arguments:
    - name: --multiomics_rna
      __merge__: ../../api/file_multiomics_rna_h5ad.yaml
      required: True
      direction: input
    - name: --multiomics_atac
      __merge__: ../../api/file_multiomics_atac_h5ad.yaml
      required: false
      direction: input
    - name: --prediction
      __merge__: ../../api/file_prediction.yaml
      required: true
      direction: output

    - name: --annotation_file
      type: file
      example: resources/grn-benchmark/supp/gencode.v45.annotation.gtf.gz
      info:
        label: annotation
        summary: "annotation file"
        file_type: gtf.gz
        columns: 
          - name: gene_name
            type: string
            required: false
          - name: annotation
            type: string
            required: false
      required: false
      direction: input
    - name: --motif_file
      type: file
      example: resources/grn-benchmark/supp/JASPAR2022-hg38.bed.gz
      info:
        label: tfmotif
        summary: "Tf motif info"
        file_type: bed.gz
        columns: 
          - name: tf_name
            type: string
            required: false
          - name: region
            type: string
            required: false
      required: false
      direction: input
    - name: --temp_dir
      type: string
      direction: input
      default: output
    - name: --num_workers
      type: integer
      direction: input
      default: 4

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_python:1.0.4
    setup:
      - type: python
        packages: [  ]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
