functionality:
  name: reformat_resources_r
  info:
    label: reformat_resources_r
    summary: "Converts data to format needed for R methods."

  arguments:
    - name: --multiomics_rna
      __merge__: ../../api/file_multiomics_rna_h5ad.yaml
      required: True
      direction: input
    - name: --multiomics_atac
      __merge__: ../../api/file_multiomics_atac_h5ad.yaml
      required: false
      direction: input
      
    - name: --rna_rds
      required: false
      direction: output
    - name: --atac_rna
      required: false
      direction: output

  resources:
    - type: r_script
      path: script.R


platforms:
  - type: docker
    image: ghcr.io/openproblems-bio/base_r:1.0.2
    # setup:
    #   - type: r
    #     packages: [dplyr, FNN, chromVAR, doParallel, BuenColors, FigR, BSgenome.Hsapiens.UCSC.hg38]

  - type: native
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
